# Generated by Django 2.2.6 on 2019-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('genre', models.CharField(choices=[('p', 'Pop'), ('r', 'Rock'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('length', models.PositiveIntegerField(help_text='in Minutes')),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(to='songs.Artist')),
            ],
        ),
    ]
